#%RAML 0.8
---
title: Sample API
baseUri: http://localhost:8080/group-vtc-service-prd/service/

/#[message.inboundProperties.'http.request.path']:
  post:
    body:
      application/json:
        example: |
          {"Jerome":"I Love Jerome"}
    responses:
      200:
        body:
          application/json:
             example: |
               {"statusCde":"0000","desc":null,"employee":{"id":2523,"staffId":"E100085225","ehrId":"E100085225","lName":"¿Ó‘∞","chName":"¿Ó‘∞","biLevel":"SSE","currtProj":null,"level":3,"aleader":{"id":2430,"staffId":null,"name":null},"password":"x4tmY9R8+9tNZepRwQQETg==","isOfic":1,"nickname":"¿Ó‘∞","bltype":"Fixed Cost","isassistant":0,"bugroup":649,"onBoadDay":"2017/05/01","releaseDay":null,"resignReason":null,"flag":0,"subpm":null},"projects":[],"leaders":[]}        